export const ActionTypes = {
    FETCH_POSTS: 'FETCH_POSTS',
    RECEIVED_USERS_POSTS: 'RECEIVED_USERS_POSTS',
    RECEIVED_POSTS: 'RECEIVED_POSTS',
    RECEIVED_RELATED_POSTS: 'RECEIVED_RELATED_POSTS',
    RECEIVED_POSTS_BY_IDS: 'RECEIVED_POSTS_BY_IDS',
    FETCH_POSTS_DONE: 'FETCH_POSTS_DONE',
    FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',

    ADDING_POST: 'ADDING_POST',
    DELETING_POST: 'DELETING_POST',
    EDITING_POST: 'EDITING_POST',
    ADD_POST_ERROR: 'ADD_POST_ERROR',
    EDIT_POST_ERROR: 'EDIT_POST_ERROR',
    POST_ADDED: 'POST_ADDED',
    POST_EDITED: 'POST_EDITED',
    POST_DELETED: 'POST_DELETED',

    FILTER_UPDATE: 'FILTER_UPDATE',
    RECEIVE_COMMENTS: 'RECEIVE_COMMENTS',
    ADD_POST: 'ADD_POST',
    UPVOTE_POST: 'UPVOTE_POST',
    DOWNVOTE_POST: 'DOWNVOTE_POST',

    ADDING_COMMENT: 'ADDING_COMMENT',
    COMMENT_ADDED: 'COMMENT_ADDED',
    EDIT_COMMENT_ERROR: 'EDIT_COMMENT_ERROR',
    REPLY_COMMENT_ERROR: 'REPLY_COMMENT_ERROR',

    EDITING_COMMENT: 'EDITING_COMMENT',
    COMMENT_EDITED: 'COMMENT_EDITED',

    DELETING_COMMENT: 'DELETING_COMMENT',
    COMMENT_DELETED: 'COMMENT_DELETED',

    ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',
    UPVOTE_COMMENT: 'UPVOTE_COMMENT',
    DOWNVOTE_COMMENT: 'DOWNVOTE_COMMENT',

    FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
    FETCH_SINGLE_POST_DONE: 'FETCH_SINGLE_POST_DONE',
    RECEIVED_SINGLE_POST: 'RECEIVED_SINGLE_POST',
    FETCH_SINGLE_POST_ERROR: 'FETCH_SINGLE_POST_ERROR',
    
    AUTH_USER: 'AUTH_USER',
    UNAUTH_USER: 'UNAUTH_USER',
    AUTH_ERROR: 'AUTH_ERROR',

    FETCH_USER: 'FETCH_USER',
    RECEIVED_USER: 'RECEIVED_USER',
    EDITING_USER: 'EDITING_USER',
    EDIT_USER_ERROR: 'EDIT_USER_ERROR',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',

     GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
     GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',
     NOTIFICATIONS_UPDATE: 'NOTIFICATIONS_UPDATE'

}