export const ActionTypes = {
    FETCH_POSTS: 'FETCH_POSTS',
    RECEIVED_POSTS: 'RECEIVED_POSTS',
    FETCH_POSTS_DONE: 'FETCH_POSTS_DONE',
    FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',

    FILTER_UPDATE: 'FILTER_UPDATE',
    RECEIVE_COMMENTS: 'RECEIVE_COMMENTS',
    ADD_POST: 'ADD_POST',
    UPVOTE_POST: 'UPVOTE_POST',
    DOWNVOTE_POST: 'DOWNVOTE_POST',
    ADD_COMMENT: 'ADD_COMMENT',
    UPVOTE_COMMENT: 'UPVOTE_COMMENT',
    DOWNVOTE_COMMENT: 'DOWNVOTE_COMMENT',

    FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
    RECEIVED_SINGLE_POST: 'RECEIVED_SINGLE_POST',
    FETCH_SINGLE_POST_DONE: 'FETCH_SINGLE_POST_DONE',
    FETCH_SINGLE_POST_ERROR: 'FETCH_SINGLE_POST_ERROR',
    
    AUTH_USER: 'AUTH_USER',
    UNAUTH_USER: 'UNAUTH_USER',
    AUTH_ERROR: 'AUTH_ERROR'

}